"""Minimal rounded ceiling luminaire; unchanged emitter envelope, metres."""
from pathlib import Path
import bpy
from mathutils import Vector
HERE=Path(__file__).resolve().parent
bpy.ops.wm.read_factory_settings(use_empty=True)
s=bpy.context.scene;s.unit_settings.system='METRIC'
m=bpy.data.materials.new('Warm white diffuser');m.diffuse_color=(.92,.89,.78,1);m.node_tree.nodes['Principled BSDF'].inputs['Base Color'].default_value=m.diffuse_color
bpy.ops.mesh.primitive_cube_add(size=1);light=bpy.context.object;light.name='Rounded ceiling diffuser';light.dimensions=(1.6,.28,.035);bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);light.data.materials.append(m)
b=light.modifiers.new('Soft rounded corners','BEVEL');b.width=.012;b.segments=4
light.modifiers.new('Weighted normals','WEIGHTED_NORMAL')
bpy.ops.object.camera_add(location=(1,-1,.8));camera=bpy.context.object;camera.rotation_euler=(-camera.location).to_track_quat('-Z','Y').to_euler();camera.data.type='ORTHO';camera.data.ortho_scale=2;s.camera=camera
bpy.ops.object.light_add(type='AREA',location=(0,-1,2));bpy.context.object.data.energy=200;bpy.context.object.data.size=3
s.world=bpy.data.worlds.new('Studio');s.world.node_tree.nodes['Background'].inputs[0].default_value=(.2,.2,.2,1)
s.render.engine='CYCLES';s.cycles.device='CPU';s.cycles.samples=16;s.render.resolution_x=900;s.render.resolution_y=500;s.render.resolution_percentage=100;s.render.filepath=str(HERE/'ceiling-light-preview.png')
bpy.ops.wm.save_as_mainfile(filepath=str(HERE/'ceiling-light.blend'));bpy.ops.render.render(write_still=True)
bpy.ops.object.select_all(action='DESELECT');light.select_set(True);bpy.context.view_layer.objects.active=light
bpy.ops.export_scene.gltf(filepath=str(HERE/'ceiling-light.glb'),export_format='GLB',use_selection=True,export_apply=True,export_cameras=False,export_lights=False)
# Explicit minimum-triangle LOD asset, also generated by the runtime as a unit cube.
light.modifiers.clear()
bpy.ops.export_scene.gltf(filepath=str(HERE/'ceiling-light-low.glb'),export_format='GLB',use_selection=True,export_apply=True,export_cameras=False,export_lights=False)
